### ISSUE TITLE
Removing symlinks on the client crashes server

### ISSUE THREAD

**Issue by brhoads** [brhoads/DigitalSignage#1]
Inside of `/media/piFolders/4` on the Pi running `rm *` causes the server to crash with:

```
{ id: '0', jsonrpc: '2.0', result: 'OK' }
File Deleted:C:\DigitalSignage\media\piFilling/Org/JSC/DA/DM/Slide13.JPG
Path: C:\DigitalSignage\media\piFilling\Org\JSC\DA\DM
{ pID: 4,
  ipaddress: '139.169.8.49',
  location: '30',
  orgcode: 'DM' }
{ pID: 84,
  ipaddress: '127.0.0.1',
  location: 'undefined',
  orgcode: 'DM' }
Server listening on port 80
{"jsonrpc":"2.0","id":"0","method":"Addons.ExecuteAddon","params":{"wait":true,"addonid":"service.digital.signage","para
ms":["play"]}}<-Posted Data
undefined

C:\...\Digital Signage\Node Code\PiBrains - Copy.js:816
                        if (alertChunk.Destination.length == 1) {
                                                  ^
TypeError: Cannot read property 'length' of undefined
    at IncomingMessage.<anonymous> (C:\...\VADER\Digital Signage\Node Code\PiBrains - Copy.js:8
16:30)
    at IncomingMessage.EventEmitter.emit (events.js:93:17)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socket.ondata (http.js:1825:22)
    at TCP.onread (net.js:404:27)
```

The code appears to be coming from the Emergency functions.

**Comment by brhoads** [comment]
Fixed in express code base.
